/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newnumberguessgame;

/**
 *
 * @author Alex
 */
public class InputRangeGui extends javax.swing.JFrame implements InputStrategy{

    public final String CUSTOM_NUMBER_FORMAT_ERROR = "You didn't enter a valid integer!";

    /**
     * Creates new form RangeInputGui
     */
    public InputRangeGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        minRangeTxt = new javax.swing.JTextField();
        maxRangeTxt = new javax.swing.JTextField();
        dashRangeLbl = new javax.swing.JLabel();
        minRangeLbl = new javax.swing.JLabel();
        maxRangeLbl = new javax.swing.JLabel();
        instructionsLbl = new javax.swing.JLabel();
        submitMinAndMaxBtn = new javax.swing.JButton();
        feedbackLbl = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        minRangeTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        maxRangeTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        dashRangeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dashRangeLbl.setText("__");

        minRangeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        minRangeLbl.setText("Min Range");

        maxRangeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        maxRangeLbl.setText("Max Range");

        instructionsLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        instructionsLbl.setText("Enter A Min And A Max Range For A Guess");

        submitMinAndMaxBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitMinAndMaxBtn.setText("Submit");
        submitMinAndMaxBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMinAndMaxBtnMouseClicked(evt);
            }
        });
        submitMinAndMaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitMinAndMaxBtnActionPerformed(evt);
            }
        });

        feedbackLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        feedbackLbl.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructionsLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minRangeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minRangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(dashRangeLbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxRangeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxRangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(submitMinAndMaxBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(feedbackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(instructionsLbl)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minRangeLbl)
                            .addComponent(maxRangeLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minRangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxRangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(dashRangeLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitMinAndMaxBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMinAndMaxBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMinAndMaxBtnMouseClicked
        String minRangeStr = "";
        String maxRangeStr = "";
        minRangeStr = minRangeTxt.getText();
        maxRangeStr = maxRangeTxt.getText();
        try {
            int minRangeInt = Integer.parseInt(minRangeStr.trim());
            int maxRangeInt = Integer.parseInt(maxRangeStr.trim());
            this.setVisible(false);
        } catch (NumberFormatException nfe) {
            feedbackLbl.setText(CUSTOM_NUMBER_FORMAT_ERROR);
        } catch (RuntimeException re) {
            feedbackLbl.setText(re.getMessage());
        }
    }//GEN-LAST:event_submitMinAndMaxBtnMouseClicked

    private void submitMinAndMaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitMinAndMaxBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMinAndMaxBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashRangeLbl;
    private javax.swing.JLabel feedbackLbl;
    private javax.swing.JLabel instructionsLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel maxRangeLbl;
    private javax.swing.JTextField maxRangeTxt;
    private javax.swing.JLabel minRangeLbl;
    private javax.swing.JTextField minRangeTxt;
    private javax.swing.JButton submitMinAndMaxBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public String[] getInput() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
